[package]
name = "vvw-app"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
description = "VVW application - Visual Virtual World audio exploration game"

[[bin]]
name = "vvw"
path = "src/main.rs"

[dependencies]
vvw-game.workspace = true
vvw-audio.workspace = true
avian2d.workspace = true
vvw-core.workspace = true
vvw-light.workspace = true
bevy.workspace = true
bevy_egui.workspace = true
clap.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
thiserror.workspace = true
serde.workspace = true
ron.workspace = true
dirs.workspace = true

[lints]
workspace = true
